// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://weqdtwfuqsncdoikucjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlcWR0d2Z1cXNuY2RvaWt1Y2psIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyMTI4NzIsImV4cCI6MjA4ODc4ODg3Mn0.rpHvibAZc58QWbyr58nPUz3xfzccsLv5l9_QtWMiyqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});